// Generated by https://quicktype.io

import { Tipo } from "./Recursos";

export interface ResultadosBusqueda {
    recursosFiltrados: RecursosFiltrado[];
}

export interface RecursosFiltrado {
    id:          string;
    nombre:      string;
    descripcion: string;
    tipo:        Tipo
    url:         string;
    usuario:     UsuarioClass;
}


export interface UsuarioClass {
    id:      string;
    usuario: string;
    activo:  boolean;
}
