import { Usuario } from "./Usuarios";

// Generated by https://quicktype.io

export interface Recursos {
    items: Item[];
    meta:  Meta;
}

export interface Item {
    id:          string;
    nombre:      string;
    descripcion: string;
    tipo:        Tipo;
    url:         string;
    usuario:     Usuario;
}


export enum Tipo {
    Imagen = "imagen",
    Video = "video",
}


export interface Meta {
    totalItems:   number;
    itemCount:    number;
    itemsPerPage: number;
    totalPages:   number;
    currentPage:  number;
}


export interface InsertarRecurso {
    nombre: string
    descripcion: string
    tipo: Tipo
    url: string
    usuarioId: string
}